gudanggaram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('debug/', include('debug.urls')),
    path('', include('login.urls')),
    path('auth/', include('authentication.urls')),
]

login/urls.py
from django.urls import path
from login.views import register, login_user, logout_user

app_name = 'login'

urlpatterns = [
    path('register/', register, name='register'),
    path('login/', login_user, name='login'),
    path('logout/', logout_user, name='logout'),
]

main/urls.py
from django.urls import path
from main.views import create_item_flutter, main_page, create_page, delete_salt

app_name = 'main'

urlpatterns = [
    path('', main_page, name='main_page'),
    path('create/', create_page, name='create'),
    path('delete/<str:hash>/', delete_salt, name='delete'),
    path('salts/<str:hash>/', main_page, name='salt_detail'),
    path('create-flutter/', create_item_flutter, name='create_item_flutter'),
]

login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
import datetime
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt


def register(request):
    form = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            messages.success(request, 'Your account has been successfully created!')
            return redirect('login:login')

    context = {'form':form}
    return render(request, 'register.html', context)

def login_user(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            response = HttpResponseRedirect(reverse("main:main_page"))
            response.set_cookie('last_login', str(datetime.datetime.now()))
            return response
        else:
            messages.info(request, 'Sorry, incorrect username or password. Please try again.')
    return render(request, 'login.html')

def logout_user(request):
    logout(request)
    response = HttpResponseRedirect(reverse('login:login'))
    response.delete_cookie('last_login')
    return response

login/templates/login.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/login.css' %}">
{% endblock meta %}

{% block content %}
<div class="login">

    <h1>Hello Again!</h1>

    <div class="form">
        <form method="POST">
            {% csrf_token %}
            <div class="form-wrapper">
                <input type="text" name="username" placeholder="Username" class="form-control username clickable"><br>
                <input type="password" name="password" placeholder="Password" class="form-control password clickable"><br>
                <input type="submit" hidden />
            </div>
            <div class="message-wrapper">
               {% if messages %}
                    <br>
                    {% for message in messages %}
                        <a>{{ message }}</a>
                    {% endfor %}
                {% endif %}
                <br>
                No account? <a href="{% url 'login:register' %}" class="clickable">Register Now</a>
            </div>
        </form>
        </div>
    </div>
</div>
{% endblock content %}

login/templates/register.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
    <link rel="stylesheet" href="{% static 'css/register.css' %}">
{% endblock meta %}

{% block content %}

<div class = "login">

    <h1>Hello World!</h1>

    <div class="form">
        <form method="POST" >
            {% csrf_token %}
            <div class="form-wrapper">
                <input type="text" name="username" maxlength="150" autocapitalize="none" autocomplete="username" autofocus required id="id_username" placeholder="Username" class="form-control username clickable"><br>
                <input type="password" name="password1" autocomplete="new-password" required id="id_password1" placeholder="Password" class="form-control password clickable"><br>
                <input type="password" name="password2" autocomplete="new-password" required id="id_password2" placeholder="Re-enter Password" class="form-control password clickable"><br>
                <input type="submit" hidden />
            </div>
        </form>
        <div class="message-wrapper">
            {% if messages %}
                <ul>
                    {% for message in messages %}
                        <li>{{ message }}</li>
                        {% endfor %}
                </ul>
            {% endif %}
        </div>
    </div>
</div>

{% endblock content %}