gudanggaram/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('debug/', include('debug.urls')),
    path('', include('login.urls')),
    path('auth/', include('authentication.urls')),
]

main/urls.py
from django.urls import path
from main.views import create_item_flutter, main_page, create_page, delete_salt

app_name = 'main'

urlpatterns = [
    path('', main_page, name='main_page'),
    path('create/', create_page, name='create'),
    path('delete/<str:hash>/', delete_salt, name='delete'),
    path('salts/<str:hash>/', main_page, name='salt_detail'),
    path('create-flutter/', create_item_flutter, name='create_item_flutter'),
]

main/models.py
from django.db import models
from django.contrib.auth.models import User

class Salts(models.Model):
    name = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True, blank=True)
    amount = models.IntegerField()
    description = models.TextField()
    sha256sum = models.CharField(max_length=64, unique=True, default=None)

    def get_absolute_url(self):
        return f"/salts/{self.sha256sum}/"

main/forms.py
from main.models import Salts
from django import forms
from django.contrib.auth.models import User

class SaltsForm(forms.ModelForm):
    class Meta:
        model = Salts
        fields = ['name', 'amount', 'description']

main/views.py
import json
from django.shortcuts import render
from main.forms import SaltsForm
from main.models import Salts
from django.http import HttpResponse, HttpResponseRedirect, JsonResponse
from django.urls import reverse
from django.contrib.auth.decorators import login_required
from hashlib import sha256
from django.views.decorators.csrf import csrf_exempt

@login_required(login_url='/login')
def main_page(request):

    salts = Salts.objects.filter(user=request.user)

    context = {
        'name': request.user.username,
        'class': 'DDP B',
        'salts': salts,
        'last_login': request.COOKIES['last_login']
    }

    return render(request, "main.html", context)

def create_page(request):
    form = SaltsForm(request.POST or None)

    if request.method == "POST" and form.is_valid():
        product = form.save(commit=False)
        product.user = request.user
        product.sha256sum = sha256(f'{product.user}-{product.name}'.encode()).hexdigest()
        product.save()
        return HttpResponseRedirect(reverse('main:main_page'))

    context = {'form': form}

    return render(request, "create.html", context)

def salt_detail(request, hash):
    salt = Salts.objects.get(sha256sum=hash)

    context = {
        'salt': salt
    }

    return render(request, "detail.html", context)

@csrf_exempt
def delete_salt(request, hash):
    print(request)
    if request.method == 'DELETE':
        print("DELETE")
        target = Salts.objects.filter(sha256sum=hash)
        target.delete()

    return HttpResponseRedirect(reverse('main:main_page'))

@csrf_exempt
def create_item_flutter(request):
    if request.method == 'POST':

        data = json.loads(request.body)

        Salts.objects.create(
            user = request.user,
            name = data["name"],
            amount = int(data["amount"]),
            description = data["desc"],
            sha256sum = sha256(f'{request.user}-{data["name"]}'.encode()).hexdigest()
        ).save()

        return JsonResponse({"status": "success"}, status=200)
    else:
        return JsonResponse({"status": "error"}, status=401)

main/templates/create.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/create.css' %}">
{% endblock meta %}

{% block content %}
<div class="create">

    <h1>Create a Salt</h1>

    <div class="form">
        <form method="POST"">
            {% csrf_token %}
            <div class="form-wrapper">
                <input type="text" name="name" placeholder="Name" class="username clickable"><br>
                <input type="number" name="amount" placeholder="Amount" class="username clickable"><br>
                <input type="text" name="description" placeholder="Description" class="username clickable"><br>
                <input type="submit" hidden />
            </div>
        </form>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block meta %}
<link rel="stylesheet" href="{% static 'css/main.css' %}">
{% endblock meta %}

{% block content %}
<div id="home">
    <div id="logo">
        <img src="{% static 'images/vector/Logo.svg' %}"/><br>
    </div>

    <div class="ornament">
        <img src="{% static 'images/vector/Ornaments1.svg' %}"/>
    </div>

    <div class="container">
        <div class="scroll">
            <img class="title" src="{% static 'images/vector/Title.svg' %}"/>
            <img class="title" src="{% static 'images/vector/Title.svg' %}"/>
        </div>
    </div>

    <p>Things here don't make sense, it's not supposed to...</p><br>
</div>
<div class="data">
    <h1 id="salt_count"></h1>
    <div class="table-wrapper">
        <table id="datatable"></table>
    </div>
    <div>
        <a href="{% url 'main:create' %}">
            <button id="button_add" class="clickable button">
                Add Salt
            </button>
        </a>
    </div>
</div>
<script src="{% static 'js/main.js' %}"></script>
{% endblock content %}